// <auto-generated />
using System;
using CourseManager.DataBase.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseManager.DataBase.SqlServer.Migrations
{
    [DbContext(typeof(CourseManagerDbContext))]
    partial class CourseManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseManager.Models.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("CourseName")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("dateTime");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("dateTime");

                    b.Property<string>("TeacherName")
                        .HasColumnType("varchar(150)");

                    b.HasKey("CourseId");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("CourseManager.Models.Entities.Student", b =>
                {
                    b.Property<long>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StudentId"));

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("dateTime");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("SurName")
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
